const personArray = [
    {img:'15_47c47e3.png',courseName:'Vue',desc:'Vue (读音 /vjuː/，类似于 view) 是一套用于构建用户界面的渐进式JavaScript框架。与其它大型框架不同的是，Vue 被设计为可以自底向上逐层应用。Vue 的核心库只关注视图层，方便与第三方库或既有项目整合。'},
    {img:'16_5149105.png',courseName:'React',desc:'Facebook的开源框架React.js，基于Virtual DOM重新定义了用户界面的开发方式，彻底革新了大家对前端框架的认识，将PHP风格的开发方式迁移到客户端应用开发。其优势在于可以与各种类库、框架搭配使用'},
    {img:'17_6dac3bd.png',courseName:'Angular',desc:'Angular (通常是指 "Angular 2+" 或 "Angular v2 及更高版本")。是一个基于 TypeScript 的 开源 Web 应用框架， 由 Google 的 Angular 团队以及社区共同领导。Angular 是由 AngularJS 的同一个开发团队完全重写的。'},
    {img:'18_061ddaf.png',courseName:'Json',desc:'JSON(JavaScript Object Notation, JS 对象简谱) 是一种轻量级的数据交换格式。它基于 ECMAScript (欧洲计算机协会制定的js规范)的一个子集，采用完全独立于编程语言的文本格式来存储和表示数据'},
    {img:'19_641febd.png',courseName:'Babel',desc:'Babel 是编写下一代 JavaScript 的编译器。 ES2015 and beyond。Babel 默认使用一组 ES2015 语法转换器，允许你使用新的语法，无需等待浏览器支持。'},
    {img:'1_2058a2b.png',courseName:'Css',desc:'层叠样式表(英文全称：Cascading Style Sheets)是一种用来表现HTML（标准通用标记语言的一个应用）或XML（标准通用标记语言的一个子集）等文件样式的计算机语言。CSS不仅可以静态地修饰网页，还可以配合各种脚本语言动态地对网页各元素进行格式化',},
    {img:'20_4f81b9b.png',courseName:'Sass',desc:'是一个最初由Hampton Catlin设计并由Natalie Weizenbaum开发的层叠样式表语言。在开发最初版本之后，Weizenbaum和Chris Eppstein继续通过SassScript来继续扩充Sass的功能。SassScript是一个在Sass文件中使用的小型脚本语言。'},
    {img:'22_da029aa.png',courseName:'Less',desc:'Less 是一门 CSS 预处理语言，它扩充了 CSS 语言，增加了诸如变量、混合（mixin）、函数等功能，让 CSS 更易维护、方便制作主题、扩充。Less 可以运行在 Node 或浏览器端。 [1]'},
    {img:'23_034e7e8.png',courseName:'Webpack',desc:'webpack它是代码编译工具，有入口，出口、loader和插件。其天生就代码分割、模块化，webpack2.0中加入tree shaking，用来提取公共代码，去掉死亡代码。'},
    {img:'24_60b405b.png',courseName:'Rollup',desc:'Rollup 是一个 JavaScript 模块打包器,可以将小块代码编译成大块复杂的代码,Rollup 对代码模块使用新的标准化格式,这些标准都包含在 JavaScript 的 ES6 版本中。'},
    {img:'25_c0f0200.png',courseName:'WebGl',desc:'WebGL(Web图形库)是一个JavaScript API,可在任何兼容的Web浏览器中渲染高性能的交互式3D和2D图形,而无需使用插件。'},
    {img:'26_335bb13.png',courseName:'Three',desc:'three.js是JavaScript编写的WebGL第三方库。提供了非常多的3D显示功能。'},
    {img:'27_b478ad5.png',courseName:'Vite',desc:'针对Vue单页面组件的无打包开发服务器，可以直接在浏览器运行请求的vue文件。'},
    {img:'28_03e8c6f.png',courseName:'Snowpack',desc:'Snowpack是用于Web应用程序开发的现代轻量级工具链,可以对标 webpack, 像 webpack 这样的工具每次更新都会重新构建部分或全部代码,这就是他的不足之处了'},
    {img:'29_fef0d05.png',courseName:'Gulp',desc:'GULP最初设计的目的是拟合力场，已经逐步发展成为模拟凝聚态物质的通用代码，可以模拟无机固体、团聚体、缺陷、表面、界面以及聚合物等。'},
    {img:'2_1ee2e6c.png',courseName:'Grunt',desc:'Grunt 是基于 Node.js 的项目构建工具。它可以自动运行你所设定的任务。Grunt 拥有数量庞大的插件,几乎任何你所要做的事情都可以用 Grunt 实现。',},
    {img:'30_af2896e.png',courseName:'TypeSript',desc:'TypeScript带来了可选的静态类型检查以及最新的ECMAScript特性。... TypeScript是JavaScript类型的超集,它可以编译成纯JavaScript。'},
    {img:'31_3f91ebd.png',courseName:'JavaScript',desc:' JavaScript 是 Web 的编程语言。 所有现代的 HTML 页面都使用 JavaScript。 JavaScript 非常容易学。'},
    {img:'32_88c4f11.png',courseName:'Eslint',desc:'ESLint 是一个插件化并且可配置的 JavaScript 语法规则和代码风格的检查工具。ESLint 能够帮你轻松写出高质量的 JavaScript 代码'},
    {img:'33_edd4f7d.png',courseName:'Tslint',desc:'ESLint 是一个插件化并且可配置的 JavaScript 语法规'},
    {img:'34_38d61ac.png',courseName:'Stylelint',desc:'ESLint 是一个插件化并且可配置的 JavaScript 语法规'},
    {img:'36_f619572.png',courseName:'Jest',desc:' JEST RUNSRUNSRUNSRUNS 入门中文文档配置获取帮助 Jest 是一个令人愉快的 JavaScript 测试框架,专注于 简洁明快'},
    {img:'37_a025f92.png',courseName:'Mocha',desc:'ESLint 是一个插件化并且可配置的 JavaScript 语法规'},
    {img:'38_377dd47.png',courseName:'chai',desc:'ESLint 是一个插件化并且可配置的 JavaScript 语法规'},
    {img:'39_31f5eb1.png',courseName:'Jasmine',desc:'JEST RUNSRUNSRUNSRUNS 入门中文文档配置获取帮助 J'},
    {img:'3_8dde7c4.png',courseName:'PhotoShop',desc:'Grunt 是基于 Node.js 的项目构建工具。它可以自动运行你',},
    {img:'40_538e40e.png',courseName:'Rize',desc:'three.js是JavaScript编写的WebGL第三方库。提供了非常'},
    {img:'41_d07ef7b.png',courseName:'Node',desc:'three.js是JavaScript编写的WebGL第三方库。提供了非常多的3D显示功能。'},
    {img:'42_d3d3f41.png',courseName:'express',desc:'Rollup 是一个 JavaScript 模块打包器,可以将小块代码编译成大块复杂的代码,R'},
    {img:'43_ec8008a.png',courseName:'Koa',desc:'Rollup 是一个 JavaScript 模块打包器,可以将小块代码编译成大块复杂的代码,R'},
    {img:'44_7d907d8.png',courseName:'Omi',desc:''},
    {img:'45_a38abb2.png',courseName:'SingleSpa',desc:''},
    {img:'46_95eaf9d.png',courseName:'Qiankun',desc:''},
    {img:'47_1e7f43d.png',courseName:'PostCss',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'48_cabf201.png',courseName:'CssNext',desc:''},
    {img:'49_31b4514.png',courseName:'Inversify',desc:''},
    {img:'0_ebefec4.png',courseName:'Flutter',desc:'',},
    {img:'12_464555f.png',courseName:'ReactNative',desc:''},
    {img:'13_f4dafcd.png',courseName:'Redux',desc:''},
    {img:'15_47c47e3.png',courseName:'Mobx',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'16_5149105.png',courseName:'uni app',desc:''},
    {img:'17_6dac3bd.png',courseName:'weex',desc:''},
    {img:'18_061ddaf.png',courseName:'Vuex',desc:''},
    {img:'19_641febd.png',courseName:'awalix',desc:''},
    {img:'1_2058a2b.png',courseName:'jsonp',desc:''},
    {img:'20_4f81b9b.png',courseName:'vscode',desc:' 在前端开发中,有一个非常好用的工具,Visual Studio Code,简称VS code。 都不用我安利VS code,大家就会乖乖的去用,无数个大言不惭的攻城狮。'},
    {img:'22_da029aa.png',courseName:'Docker',desc:'Docker 是一个开源的应用容器引擎，让开发者可以打包他们的应用以及依赖包到一个可移植的镜像中，然后发布到任何流行的 Linux或Windows 机器上，也可以实现虚拟化。容器是完全使用沙箱机制，相互之间不会有任何接口。'},
    {img:'23_034e7e8.png',courseName:'git',desc:'Git（读音为/gɪt/）是一个开源的分布式版本控制系统，可以有效、高速地处理从很小到非常大的项目版本管理。'},
    {img:'24_60b405b.png',courseName:'svn',desc:'SVN是subversion的缩写，是一个开放源代码的版本控制系统，通过采用分支管理系统的高效管理，简而言之就是用于多个人共同开发同一个项目，实现共享资源，实现最终集中式的管理。'},
    {img:'25_c0f0200.png',courseName:'LeetCode',desc:'力扣（LeetCode）是领扣网络旗下专注于程序员技术成长和企业技术人才服务的品牌。源自美国硅谷，力扣为全球程序员提供了专业的IT 技术职业化提升平台，有效帮助程序员实现快速进步和长期成长'},
    {img:'26_335bb13.png',courseName:'Jenkins',desc:'Jenkins是一个开源软件项目，是基于Java开发的一种持续集成工具，用于监控持续重复的工作，旨在提供一个开放易用的软件平台，使软件的持续集成变成可能。'},
    {img:'27_b478ad5.png',courseName:'Html',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Internet资源连接为一个逻辑整体。HTML文本是由HTML命令组成的描述性文本，HTML命令可以说明文字，图形、动画、声音、表格、链接等'},
    {img:'28_03e8c6f.png',courseName:'',desc:''},
    {img:'29_fef0d05.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'2_1ee2e6c.png',courseName:'',desc:'Rollup 是一个 JavaScript 模块打包器,可以将小块代码编译成大块复杂的代码,R'},
    {img:'30_af2896e.png',courseName:'',desc:''},
    {img:'31_3f91ebd.png',courseName:'',desc:''},
    {img:'32_88c4f11.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'33_edd4f7d.png',courseName:'',desc:''},
    {img:'34_38d61ac.png',courseName:'',desc:''},
    {img:'36_f619572.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'37_a025f92.png',courseName:'',desc:''},
    {img:'38_377dd47.png',courseName:'',desc:''},
    {img:'39_31f5eb1.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'3_8dde7c4.png',courseName:'',desc:'',},
    {img:'40_538e40e.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'41_d07ef7b.png',courseName:'',desc:''},
    {img:'42_d3d3f41.png',courseName:'',desc:''},
    {img:'43_ec8008a.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'44_7d907d8.png',courseName:'',desc:''},
    {img:'45_a38abb2.png',courseName:'',desc:''},
    {img:'46_95eaf9d.png',courseName:'',desc:'Rollup 是一个 JavaScript 模块打包器,可以将小块代码编译成大块复杂的代码,R'},
    {img:'47_1e7f43d.png',courseName:'',desc:''},
    {img:'48_cabf201.png',courseName:'',desc:''},
    {img:'49_31b4514.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'0_ebefec4.png',courseName:'',desc:''},
    {img:'12_464555f.png',courseName:'',desc:''},
    {img:'13_f4dafcd.png',courseName:'',desc:''},
    {img:'15_47c47e3.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'16_5149105.png',courseName:'',desc:''},
    {img:'17_6dac3bd.png',courseName:'',desc:''},
    {img:'18_061ddaf.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'19_641febd.png',courseName:'',desc:''},
    {img:'1_2058a2b.png',courseName:'',desc:'',},
    {img:'20_4f81b9b.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'22_da029aa.png',courseName:'',desc:''},
    {img:'23_034e7e8.png',courseName:'',desc:''},
    {img:'24_60b405b.png',courseName:'',desc:''},
    {img:'25_c0f0200.png',courseName:'',desc:''},
    {img:'26_335bb13.png',courseName:'',desc:''},
    {img:'27_b478ad5.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'28_03e8c6f.png',courseName:'',desc:''},
    {img:'29_fef0d05.png',courseName:'',desc:''},
    {img:'2_1ee2e6c.png',courseName:'',desc:'',},
    {img:'30_af2896e.png',courseName:'',desc:''},
    {img:'31_3f91ebd.png',courseName:'',desc:''},
    {img: '32_88c4f11.png',courseName:'',desc:'',},
    {img: '33_edd4f7d.png',courseName:'',desc:'',},
    {img:'34_38d61ac.png',courseName:'',desc:''},
    {img:'36_f619572.png',courseName:'',desc:''},
    {img: '37_a025f92.png',courseName:'',desc:'',},
    {img:'38_377dd47.png',courseName:'',desc:''},
    {img:'39_31f5eb1.png',courseName:'',desc:''},
    {img:'3_8dde7c4.png',courseName:'',desc:'',},
    {img:'40_538e40e.png',courseName:'',desc:''},
    {img: '41_d07ef7b.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte',},
    {img:'42_d3d3f41.png',courseName:'',desc:''},
    {img:'43_ec8008a.png',courseName:'',desc:''},
    {img:'44_7d907d8.png',courseName:'',desc:''},
    {img:'45_a38abb2.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'46_95eaf9d.png',courseName:'',desc:''},
    {img:'47_1e7f43d.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'48_cabf201.png',courseName:'',desc:'HTML称为超文本标记语言，是一种标识性的语言。它包括一系列标签．通过这些标签可以将网络上的文档格式统一，使分散的Inte'},
    {img:'49_31b4514.png',courseName:'',desc:''},
    {img:'8_3a9dd21.png',courseName:'',desc:''},
    {img:'8_3a9dd21.png',courseName:'',desc:''},
    {img:'8_3a9dd21.png',courseName:'',desc:''},
  ];

 export default personArray